[package]
name = "awskctx"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
