[package]
name = "staturl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
statrs = "0.18.0"
stats-cli = "3.0.1"
