[package]
name = "staturl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
statrs = "0.18"
stats-cli = "3.0"
